### ISSUE TITLE
How to connect ip and port 

### ISSUE THREAD

**Issue by Anjillou** [SilvVF/HoyoModManagerGo#1]
How to connect ip and port please

**Comment by SilvVF** [comment]
it just uses whatever your pc's IP address is when you run ipconfig. All the endpoints have basic auth but there is no option to set username and password yet. 

use basic auth credentials "username" and "password" when calling any of the endpoints. 

if using android app set username to "username" and password to "password"
set server address to "IP:Port"

**Comment by SilvVF** [comment]
Added the options to change username and password or set to none 
[v0.0.6](https://github.com/SilvVF/HoyoModManagerGo/releases/tag/v0.0.6)
[Server Handlers](https://github.com/SilvVF/HoyoModManagerGo/blame/c9e28e3db2fb9ec295ab02f4f9714d8622743209/pkg/server/server.go#L175-L182)
```go
	mux.HandleFunc("GET /data", basicAuthMiddleware(dataHandler(s.db)))
	mux.HandleFunc("GET /data/{game}", basicAuthMiddleware(gameDataHandler(s.db)))
	mux.HandleFunc("POST /update/mod", basicAuthMiddleware(updateModHandler(s.db)))
	mux.HandleFunc("POST /generate", basicAuthMiddleware(generateHandler(s.generator)))
	mux.HandleFunc("GET /poll-generation", basicAuthMiddleware(pollGenerationHandler()))
```

**Comment by Anjillou** [comment]
Thanks
